### ISSUE TITLE
Empty string should not be a tag

### ISSUE THREAD

**Issue by christickner** [phpmentoring/testapp#7]
We need to prevent empty strings from being saved as taxonomyTerms.

Steps I did, with an empty db:
1. Sign up
2. Goto edit profile
3. check "I want to be a mentor" and type in mentor tags
4. leave apprentice tags blank
5. Save

The "taxonomyTerms" table now contains an apprentice term that is blank.

**Comment by dragonmantank** [comment]
Fixed with 410e96c

**Comment by gabidavila** [comment]
I can confirm this bug is still happening.

```
mysql> use phpmentoring;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select * from taxonomyTerms;
+----+------+-------------+---------+---------------+
| id | name | description | enabled | vocabulary_id |
+----+------+-------------+---------+---------------+
|  1 |      |             |       0 |             1 |
|  2 |      |             |       0 |             2 |
|  3 |      |             |       0 |             3 |
+----+------+-------------+---------+---------------+
3 rows in set (0.00 sec)

```

Also a script should be run on the `userTags` table later to clean the assignment of empty tags to the users.
